#pragma once

// RESET
#define TERM_COLOR_RESET "\x1B[0m"
// BLACK
#define TERM_COLOR_BLACK "\x1B[0;30m"
// RED
#define TERM_COLOR_RED "\x1B[0;31m"
// GREEN
#define TERM_COLOR_GREEN "\x1B[0;32m"
// YELLOW
#define TERM_COLOR_YELLOW "\x1B[0;33m"
// BLUE
#define TERM_COLOR_BLUE "\x1B[0;34m"
// PURPLE
#define TERM_COLOR_PURPLE "\x1B[0;35m"
// CYAN
#define TERM_COLOR_CYAN "\x1B[0;36m"
// WHITE
#define TERM_COLOR_WHITE "\x1B[0;37m"
// BLACK
#define TERM_COLOR_BLACK_BOLD "\x1B[1;30m"
// RED
#define TERM_COLOR_RED_BOLD "\x1B[1;31m"
// GREEN
#define TERM_COLOR_GREEN_BOLD "\x1B[1;32m"
// YELLOW
#define TERM_COLOR_YELLOW_BOLD "\x1B[1;33m"
// BLUE
#define TERM_COLOR_BLUE_BOLD "\x1B[1;34m"
// PURPLE
#define TERM_COLOR_PURPLE_BOLD "\x1B[1;35m"
// CYAN
#define TERM_COLOR_CYAN_BOLD "\x1B[1;36m"
// WHITE
#define TERM_COLOR_WHITE_BOLD "\x1B[1;37m"
// BLACK
#define TERM_COLOR_BLACK_UNDERLINED "\x1B[4;30m"
// RED
#define TERM_COLOR_RED_UNDERLINED "\x1B[4;31m"
// GREEN
#define TERM_COLOR_GREEN_UNDERLINED "\x1B[4;32m"
// YELLOW
#define TERM_COLOR_YELLOW_UNDERLINED "\x1B[4;33m"
// BLUE
#define TERM_COLOR_BLUE_UNDERLINED "\x1B[4;34m"
// PURPLE
#define TERM_COLOR_PURPLE_UNDERLINED "\x1B[4;35m"
// CYAN
#define TERM_COLOR_CYAN_UNDERLINED "\x1B[4;36m"
// WHITE
#define TERM_COLOR_WHITE_UNDERLINED "\x1B[4;37m"
// BLACK
#define TERM_COLOR_BLACK_BACKGROUND "\x1B[40m"
// RED
#define TERM_COLOR_RED_BACKGROUND "\x1B[41m"
// GREEN
#define TERM_COLOR_GREEN_BACKGROUND "\x1B[42m"
// YELLOW
#define TERM_COLOR_YELLOW_BACKGROUND "\x1B[43m"
// BLUE
#define TERM_COLOR_BLUE_BACKGROUND "\x1B[44m"
// PURPLE
#define TERM_COLOR_PURPLE_BACKGROUND "\x1B[45m"
// CYAN
#define TERM_COLOR_CYAN_BACKGROUND "\x1B[46m"
// WHITE
#define TERM_COLOR_WHITE_BACKGROUND "\x1B[47m"
// BLACK
#define TERM_COLOR_BLACK_BRIGHT "\x1B[0;90m"
// RED
#define TERM_COLOR_RED_BRIGHT "\x1B[0;91m"
// GREEN
#define TERM_COLOR_GREEN_BRIGHT "\x1B[0;92m"
// YELLOW
#define TERM_COLOR_YELLOW_BRIGHT "\x1B[0;93m"
// BLUE
#define TERM_COLOR_BLUE_BRIGHT "\x1B[0;94m"
// PURPLE
#define TERM_COLOR_PURPLE_BRIGHT "\x1B[0;95m"
// CYAN
#define TERM_COLOR_CYAN_BRIGHT "\x1B[0;96m"
// WHITE
#define TERM_COLOR_WHITE_BRIGHT "\x1B[0;97m"
// BLACK
#define TERM_COLOR_BLACK_BOLD_BRIGHT "\x1B[1;90m"
// RED
#define TERM_COLOR_RED_BOLD_BRIGHT "\x1B[1;91m"
// GREEN
#define TERM_COLOR_GREEN_BOLD_BRIGHT "\x1B[1;92m"
// YELLOW
#define TERM_COLOR_YELLOW_BOLD_BRIGHT "\x1B[1;93m"
// BLUE
#define TERM_COLOR_BLUE_BOLD_BRIGHT "\x1B[1;94m"
// PURPLE
#define TERM_COLOR_PURPLE_BOLD_BRIGHT "\x1B[1;95m"
// CYAN
#define TERM_COLOR_CYAN_BOLD_BRIGHT "\x1B[1;96m"
// WHITE
#define TERM_COLOR_WHITE_BOLD_BRIGHT "\x1B[1;97m"
// BLACK
#define TERM_COLOR_BLACK_BACKGROUND_BRIGHT "\x1B[0;100m"
// RED
#define TERM_COLOR_RED_BACKGROUND_BRIGHT "\x1B[0;101m"
// GREEN
#define TERM_COLOR_GREEN_BACKGROUND_BRIGHT "\x1B[0;102m"
// YELLOW
#define TERM_COLOR_YELLOW_BACKGROUND_BRIGHT "\x1B[0;103m"
// BLUE
#define TERM_COLOR_BLUE_BACKGROUND_BRIGHT "\x1B[0;104m"
// PURPLE
#define TERM_COLOR_PURPLE_BACKGROUND_BRIGHT "\x1B[0;105m"
// CYAN
#define TERM_COLOR_CYAN_BACKGROUND_BRIGHT "\x1B[0;106m"
// WHITE
#define TERM_COLOR_WHITE_BACKGROUND_BRIGHT "\x1B[0;107m"
