function(has_name_component SOME_PATH NAME_COMPONENT HAS_COMPONENT_VN)
    set(HAS_COMPONENT false)
    while (SOME_PATH)
        get_filename_component(PARENT ${SOME_PATH} PATH)
        get_filename_component(NAME   ${SOME_PATH} NAME)
        if ("${NAME}" STREQUAL "${NAME_COMPONENT}")
            set(HAS_COMPONENT true)
            set(SOME_PATH)
        else()
            if ("${PARENT}" STREQUAL "/")
                set(SOME_PATH)
            else()    
                set(SOME_PATH ${PARENT})
            endif()    
        endif()
    endwhile()
    set(${HAS_COMPONENT_VN} ${HAS_COMPONENT} PARENT_SCOPE)
endfunction()
